stages:
  data_ingestion:
    cmd: uv run src/Classifier/pipeline/data_ingestion_pipeline.py
    deps:
      - src/Classifier/components/data_ingestion.py
      - config/config.yaml
    outs:
      - artifact/data_ingestion/test
      - artifact/data_ingestion/train
  
  model_training:
    cmd: uv run src/Classifier/pipeline/model_training_pipeline.py
    deps:
      - src/Classifier/components/train.py
      - artifact/data_ingestion/train
      - config/config.yaml
    outs:
      - artifact/model/model.pth
      - artifact/run_id.txt
  
  model_eval:
    cmd: uv run src/Classifier/pipeline/model_eval_pipeline.py
    deps:
      - src/Classifier/components/model_eval.py
      - artifact/data_ingestion/test
      - config/config.yaml
      - artifact/model/model.pth
    metrics:
      - artifact/model_eval/metric.json:
          cache: false