artifact_root: artifact

data_ingestion:
  root_dir: artifact/data_ingestion
  data_path: "https://drive.google.com/uc?export=download&id=1N-XqibEcyHezLK1IYH0Us_81UqhEDuMH"
  zip_file: artifact/data_ingestion/data.zip
  unzip_file: artifact/data_ingestion

model_building:
  root_dir: artifact/model
  train_data_file: artifact/data_ingestion/archive/train
  model: model.pth
